### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by GermXSanitizer** [AXDZ/FakeNnections#2]
Seems like they do some sort of validation on the fake connection's ID

**Comment by Luciferexe** [comment]
Yeah it is dead

**Comment by unlimitedcoder2** [comment]
Any fix?

**Comment by AXDZ** [comment]
Doesnt ssem to work for now, ill try to work on it

**Comment by AXDZ** [comment]
Otherwise release that it has been fixed

**Comment by unlimitedcoder2** [comment]
Unfortunately I've never been able to get my discord to recognise my skypebso I can't see what new fields are being passed in the request. Though it appears to be a new field called provider_id I think

**Comment by Luciferexe** [comment]
I think it is just broken or they patched it or something like that

**Comment by unlimitedcoder2** [comment]
Like completely removed the option to link non oauth accounts?

**Comment by AXDZ** [comment]
Not sure i havent reviewed yet ill make sure to do after i make a new repo later

**Comment by 2Gabriel** [comment]
doesn't work anymore ???
